/**
 * Agent configuration snippets, built here in the browser.
 *
 * `GET /api/agent-connect` returns the bearer token in a response body and is
 * never called by this app — a page served from a third-party origin must not
 * put the token into a document that origin can see. Everything below is
 * assembled from what already lives in this browser's localStorage.
 *
 * Nothing in this module fetches, and nothing in it logs.
 */

import { normalizeBaseUrl } from "@/lib/settings";

export type AgentTargetId = "claude-code" | "claude-desktop" | "cursor";

export type AgentTarget = {
  id: AgentTargetId;
  label: string;
  /** How the config reaches the client, in the user's words. */
  where: string;
  /** "shell" renders as a command line; "json" as a config file body. */
  kind: "shell" | "json";
  snippet: string;
  /** True when the snippet embeds the bearer token. */
  carriesToken: boolean;
  note: string;
};

const TOKEN_PLACEHOLDER = "<your token>";

export type AgentConfigInput = {
  baseUrl: string;
  token: string;
};

/** The HTTP MCP endpoint of the server this browser is pointed at. */
export function mcpEndpoint(baseUrl: string): string {
  return `${normalizeBaseUrl(baseUrl)}/mcp`;
}

/**
 * A quoted shell argument. The token is generated by the server and is
 * alphanumeric in practice, but a value that reaches a command line is quoted
 * on principle rather than on inspection.
 */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export function buildAgentTargets(input: AgentConfigInput): AgentTarget[] {
  const url = mcpEndpoint(input.baseUrl);
  const token = input.token || TOKEN_PLACEHOLDER;
  const remote = {
    mcpServers: {
      mailmux: {
        url,
        headers: { Authorization: `Bearer ${token}` },
      },
    },
  };

  return [
    {
      id: "claude-code",
      label: "Claude Code",
      where: "Run this once in any terminal.",
      kind: "shell",
      snippet: `claude mcp add --transport http mailmux ${shellQuote(url)} --header ${shellQuote(
        `Authorization: Bearer ${token}`,
      )}`,
      carriesToken: true,
      note: "Adds mailmux for the current project. Add --scope user to make it available everywhere.",
    },
    {
      id: "claude-desktop",
      label: "Claude Desktop",
      where:
        "Settings → Developer → Edit config, then paste this into claude_desktop_config.json and restart the app.",
      kind: "json",
      snippet: JSON.stringify(
        { mcpServers: { mailmux: { command: "mailmux", args: ["mcp"] } } },
        null,
        2,
      ),
      carriesToken: false,
      // The stdio CLI is a second entry point into the same MailService, so it
      // reads the same data directory and needs no token — which is why this
      // one snippet is safe to paste anywhere.
      note: "Claude Desktop starts mailmux itself over stdio. No token is involved, and your server does not need to be running.",
    },
    {
      id: "cursor",
      label: "Cursor",
      where:
        "Paste into ~/.cursor/mcp.json for every project, or .cursor/mcp.json inside one project.",
      kind: "json",
      snippet: JSON.stringify(remote, null, 2),
      carriesToken: true,
      note: "Cursor connects over HTTP, so mailmux serve has to be running.",
    },
  ];
}

/**
 * The generic remote-MCP block, for a client that is not in the list above.
 * Same shape the settings panel has always shown.
 */
export function genericMcpSnippet(input: AgentConfigInput): string {
  return JSON.stringify(
    {
      mcpServers: {
        mailmux: {
          url: mcpEndpoint(input.baseUrl),
          headers: {
            Authorization: `Bearer ${input.token || TOKEN_PLACEHOLDER}`,
          },
        },
      },
    },
    null,
    2,
  );
}
