/**
 * Agent configuration snippets, built here in the browser.
 *
 * `GET /api/agent-connect` returns the bearer token in a response body and is
 * never called by this app — a page served from a third-party origin must not
 * put the token into a document that origin can see. Everything below is
 * assembled from what already lives in this browser's localStorage.
 *
 * Nothing in this module fetches, and nothing in it logs.
 */

import { normalizeBaseUrl } from "@/lib/settings";

export type AgentTargetId =
  | "claude-code"
  | "grok"
  | "claude-desktop"
  | "cursor";

export type AgentTarget = {
  id: AgentTargetId;
  label: string;
  /** How the config reaches the client, in the user's words. */
  where: string;
  /** "shell" renders as a command line; "json" as a config file body. */
  kind: "shell" | "json";
  snippet: string;
  /** True when the snippet embeds the bearer token. */
  carriesToken: boolean;
  note: string;
  /**
   * One-click path, when the client has one. Rendered as the primary action;
   * the snippet then becomes the manual alternative.
   */
  download?: { href: string; filename: string; action: string };
};

const TOKEN_PLACEHOLDER = "<your token>";

export type AgentConfigInput = {
  baseUrl: string;
  token: string;
};

/** The HTTP MCP endpoint of the server this browser is pointed at. */
export function mcpEndpoint(baseUrl: string): string {
  return `${normalizeBaseUrl(baseUrl)}/mcp`;
}

/**
 * A quoted shell argument. The token is generated by the server and is
 * alphanumeric in practice, but a value that reaches a command line is quoted
 * on principle rather than on inspection.
 */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export function buildAgentTargets(input: AgentConfigInput): AgentTarget[] {
  const url = mcpEndpoint(input.baseUrl);
  const token = input.token || TOKEN_PLACEHOLDER;
  const remote = {
    mcpServers: {
      mailmux: {
        url,
        headers: { Authorization: `Bearer ${token}` },
      },
    },
  };

  return [
    {
      id: "claude-code",
      label: "Claude Code",
      where: "Run this once in any terminal.",
      kind: "shell",
      snippet: `claude mcp add --transport http mailmux ${shellQuote(url)} --header ${shellQuote(
        `Authorization: Bearer ${token}`,
      )}`,
      carriesToken: true,
      note: "Adds mailmux for the current project. Add --scope user to make it available everywhere.",
    },
    {
      id: "grok",
      label: "Grok",
      where: "Run this once in any terminal.",
      kind: "shell",
      snippet: `grok mcp add --transport http mailmux ${shellQuote(url)} --header ${shellQuote(
        `Authorization: Bearer ${token}`,
      )}`,
      carriesToken: true,
      note: "Writes ~/.grok/config.toml. Then start a grok session and paste the prompt below — or press Start next to Grok in the Agents list if the CLI is on this machine.",
    },
    {
      id: "claude-desktop",
      label: "Claude Desktop",
      where: "Download the connector, then double-click the file. Claude Desktop opens, shows what it does, and installs it — nothing to configure.",
      kind: "json",
      // The manual fallback, for a Claude Desktop that cannot open .mcpb
      // files. It carries no token: the connector reads bearer.token itself.
      snippet: JSON.stringify(
        { mcpServers: { mailmux: { command: "mailmux", args: ["mcp"] } } },
        null,
        2,
      ),
      carriesToken: false,
      note: "The connector finds your local server and its token on its own — mailmux just has to be running. The manual snippet goes into claude_desktop_config.json (Settings → Developer → Edit config) and needs the mailmux CLI on your PATH instead.",
      download: {
        // Served by the user's own mailmux server, built from apps/mcpb.
        href: `${normalizeBaseUrl(input.baseUrl)}/mailmux.mcpb`,
        filename: "mailmux.mcpb",
        action: "Download for Claude Desktop",
      },
    },
    {
      id: "cursor",
      label: "Cursor",
      where:
        "Paste into ~/.cursor/mcp.json for every project, or .cursor/mcp.json inside one project.",
      kind: "json",
      snippet: JSON.stringify(remote, null, 2),
      carriesToken: true,
      note: "Cursor connects over HTTP, so mailmux serve has to be running.",
    },
  ];
}

/**
 * The generic remote-MCP block, for a client that is not in the list above.
 * Same shape the settings panel has always shown.
 */
export function genericMcpSnippet(input: AgentConfigInput): string {
  return JSON.stringify(
    {
      mcpServers: {
        mailmux: {
          url: mcpEndpoint(input.baseUrl),
          headers: {
            Authorization: `Bearer ${input.token || TOKEN_PLACEHOLDER}`,
          },
        },
      },
    },
    null,
    2,
  );
}
